version: '3.3'

services:
  db:
    image: percona:5.7.22
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  db-arm:
    platform: linux/x86_64
    image: biarms/mysql:5.7
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root